version: "3.5"
services:
  reth:
    image: "reth.reth.dnp.dappnode.eth:0.0.1"
    build:
      context: .
      args:
        UPSTREAM_VERSION: v0.1.0-alpha.4
    ports:
      - "30405:30405/tcp"
      - "30405:30405/udp"
    volumes:
      - "rethdata:/home/reth/.local/share"
    environment:
      P2P_PORT: 30405
      EXTRA_OPTs: "--http.api=rpc,eth,web3,net,debug,trace,txpool"
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          memory: 32768M
volumes:
  rethdata: {}
